# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GenerarDocumentos
                                 A QGIS plugin
 Generar documentos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-27
        copyright            : (C) 2020 by oliver
        email                : oliver
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GenerarDocumentos class from file GenerarDocumentos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .generar_documentos import GenerarDocumentos
    return GenerarDocumentos(iface)
