# -*- coding: utf-8 -*-
"""
/***************************************************************************
 operaciones
                                 A QGIS plugin
 asigna operaciones segun el rol
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-10-27
        git sha              : $Format:%H$
        copyright            : (C) 2020 by 1
        email                : 1
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5 import uic
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QTableWidgetItem
from PyQt5.QtWidgets import QAction, QMessageBox
from PyQt5 import QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import os, requests, json
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .asigna_operaciones_dialog import operacionesDialog
import os.path, requests, json

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'asigna_operaciones_dialog_base.ui'))
class operaciones(QtWidgets.QDialog, FORM_CLASS):
    """QGIS Plugin Implementation."""

    def __init__(self, iface, CFG = None, UTI = None, parent=None, nuevo = False):
        super(operaciones, self).__init__(parent, \
            flags=Qt.WindowCloseButtonHint)
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'operaciones_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&operaciones')
        self.dlg = operacionesDialog(parent = iface.mainWindow())
        self.dlg.twOperaciones.clicked.connect(self.traerOperaciones)
        self.dlg.btGuardar.clicked.connect(self.editarOperaciones)
        self.dlg.btCerrar.clicked.connect(self.event_cancelar)
        self.dlg.twOperaciones.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.dlg.twOperaciones_2.hideColumn(1)
        self._seleccionados = []
        self.nuevo = nuevo
        self.CFG = CFG
        self.UTI = UTI
        self.headers = {'Content-Type': 'application/json'}
        self.usuarios = []
        self.roles = []
        self.setupUi(self)

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
       

       

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('operaciones', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/asigna_operaciones/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&operaciones'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = operacionesDialog()
            

        '''datos=[1,2,3]'''
        
        self.dlg.twOperaciones.clearContents()
        self.dlg.twOperaciones.setRowCount(0)
        self.usuarios = self.consumeWSGeneral(url_cons = self.CFG.url_AU_getAllAuthorities)

        if not self.usuarios:
             return

                # mostrar usuarios en tabla
        self.dlg.twOperaciones.setRowCount(len(self.usuarios))
        for x in range(0, len(self.usuarios)):
            
            item2 = QTableWidgetItem(self.usuarios[x])
            self.dlg.twOperaciones.setItem(x, 0, item2)
           

        
        # show the dialog
        self.dlg.setModal(True)
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass


    def traerOperaciones(self):
        #self.createAlert("Si conecto", QMessageBox().Information, "Si se hizo")
        self.dlg.twOperaciones_2.clearContents()
        self.dlg.twOperaciones_2.setRowCount(0)



        row = self.dlg.twOperaciones.currentRow()
        rol = self.dlg.twOperaciones.item(row,0)

        #print('---------------')
        #print(rol.text())
        #print(self.CFG.url_AU_getAllRole + rol.text())
        #print('---------------')


        self.roles = self.consumeWSGeneral(url_cons = self.CFG.url_AU_getAllRole + rol.text())
        #print(self.roles)
        if not self.roles:
             return

                # mostrar usuarios en tabla
        self.dlg.twOperaciones_2.setRowCount(len(self.roles))
        for x in range(0, len(self.roles)):
            

           
            check = QTableWidgetItem(self.roles[x]['nombre'])

            #check = QTableWidgetItem(self.roles[x]['asignado'])
            check.setFlags(QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
            if self.roles[x]['asignado'] == False:
                check.setCheckState(QtCore.Qt.Unchecked)
            else:
                check.setCheckState(QtCore.Qt.Checked)

            #self.dlg.twOperaciones_2.setItem(x,0,check)
            
            self.dlg.twOperaciones_2.setItem(x, 0, check)
            self.dlg.twOperaciones_2.setItem(x, 1, QtWidgets.QTableWidgetItem(str(self.roles[x]['id'])))


    def editarOperaciones(self):

        if self.dlg.twOperaciones_2.rowCount() > 0:


            row_2 = self.dlg.twOperaciones.currentRow()
            rol = self.dlg.twOperaciones.item(row_2,0)
            # obtenemos el numero total de registros en el qtablewidget
            allRows = self.dlg.twOperaciones_2.rowCount()

            # inicializamos variable (lista) donde se agregan el texto de los registros activos por check
            self._seleccionados = []

            # se itera los registros del qtablewidget
            for row in range(0, allRows):

                # se obtiene el item segun la iteracion
                # el registro (row) en la posicion 0 (columna 0) 
                # en este ejmplo solo se cuenta con una columna por eso la posicion 0
                item = self.dlg.twOperaciones_2.item(row, 0)
                item3 = self.dlg.twOperaciones_2.item(row, 1)

                # se verifica que el checkbox este seleccionado
                if item.checkState() == 2: # True
                    self._seleccionados.append(item3.text())

            
            envio = {}
            envio['permisos'] = self._seleccionados
            envio['rol'] = rol.text()
            resp = self.guardarOperacion(nuevo = self.nuevo, url = (self.CFG.url_AU_actualizarOperaciones), envio = envio)

            if resp == 'OK':
                self.createAlert('Operaciones Asignadas Correctamente', QMessageBox().Information)
            else:
                return
            
            #self.dlg.accept()       
            print(envio)  

        

    def event_cancelar(self):
        self.dlg.close()

    def guardarOperacion(self, nuevo = False, url = '', envio = {}):
        data = ""
        
        # envio - el objeto de tipo dict, es el json que se va a guardar
        # se debe hacer la conversion para que sea aceptado por el servicio web
        jsonEnv = json.dumps(envio)
        
        try:
            # header para obtener el token
            self.headers['Authorization'] = self.UTI.obtenerToken()

            if nuevo:
                response = requests.put(url, headers = self.headers, data = jsonEnv)
           

                # ejemplo con put, url, header y body o datos a enviar
               

        except requests.exceptions.RequestException as e:
            self.createAlert("Error de servidor, 'guardarOperacion()' '" + str(e) + "'", QMessageBox().Critical, "Error de servidor")
            return str(e)

        if response.status_code == 403:
            self.createAlert('Sin Permisos para ejecutar la accion', QMessageBox().Critical, "Operaciones")
            return None
           
        elif response.status_code >= 300:
            self.createAlert('Error en peticion "guardarOperacion()":\n' + response.text, QMessageBox().Critical, "Error de servidor")
            return response.text

        return 'OK'

    def consumeWSGeneral(self, url_cons = ""):

        url = url_cons
        data = ""

        try:
            self.headers['Authorization'] = self.UTI.obtenerToken()
            response = requests.get(url, headers = self.headers)
        except requests.exceptions.RequestException as e:
            self.createAlert("Error de servidor, 'consumeWSGeneral()'" + str(e) + "'", QMessageBox().Critical, "Error de servidor")
            return

        if response.status_code == 200:
            data = response.content
                   
        else:
            self.createAlert('Error en peticion "consumeWSGeneral()":\n' + response.text, QMessageBox().Critical, "Error de servidor")
            return

        return json.loads(data)
    def createAlert(self, mensaje, icono = QMessageBox().Critical, titulo = 'Operaciones'):
        #Create QMessageBox
        self.msg = QMessageBox()
        #Add message
        self.msg.setText(mensaje)
        #Add icon of critical error
        self.msg.setIcon(icono)
        #Add tittle
        self.msg.setWindowTitle(titulo)
        #Show of message dialog
        self.msg.show()
         # Run the dialog event loop
        result = self.msg.exec_()
