# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VentanaDibujoV3
                                 A QGIS plugin
 VentanaDibujoV3
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-07-03
        git sha              : $Format:%H$
        copyright            : (C) 2018 by VentanaDibujoV3
        email                : VentanaDibujoV3
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .VentanaDibujoV3_dialog import VentanaDibujoV3Dialog
import os.path


from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt, QSize
from PyQt5.QtGui import QIcon, QColor, QCursor, QPixmap
from PyQt5.QtWidgets import QAction, QWidget,QVBoxLayout, QPushButton, QMessageBox, QTableWidget, QTableWidgetItem
from PyQt5 import QtWidgets

from qgis.core import *
from qgis.utils import iface, loadPlugin, startPlugin, reloadPlugin
from qgis.gui import QgsLayerTreeView, QgsMapToolEmitPoint, QgsMapTool, QgsRubberBand, QgsVertexMarker

import os.path
import os, json, requests, sys
from osgeo import ogr, osr

from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt, QSize
from PyQt5.QtGui import QIcon, QColor, QCursor, QPixmap
from PyQt5.QtWidgets import QAction, QWidget,QVBoxLayout, QPushButton, QMessageBox, QTableWidget, QTableWidgetItem
from PyQt5 import QtWidgets

from qgis.core import *
from qgis.utils import iface, loadPlugin, startPlugin, reloadPlugin
from qgis.gui import QgsLayerTreeView, QgsMapToolEmitPoint, QgsMapTool, QgsRubberBand, QgsVertexMarker

import os.path
import os, json, requests, sys
from osgeo import ogr, osr
#from ...menu import desact

class VentanaDibujoV3:
    """QGIS Plugin Implementation."""

    def __init__(self, iface, pluginE):
       
        self.pluginE = pluginE 

        self.dlg = VentanaDibujoV3Dialog(pluginV=self, parent = iface.mainWindow())
        self.dlg.botonAgregar.clicked.connect(self.confirmarFeature)
        self.dlg.botonCancelar.clicked.connect(self.cancelarFeature)
        #self.dlg.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)

        self.listaAtributos = []
        self.comboTipoConst = QtWidgets.QComboBox()
        self.comboConstEsp = QtWidgets.QComboBox()
        self.comboTipoAs = QtWidgets.QComboBox()
        self.comboTipoConst = QtWidgets.QComboBox()
        self.comboCveVus = QtWidgets.QComboBox()
              
        self.posibleMostar = True   
        
        self.ultimo = 0
        self.posibleCerrar = False
        self.headers = {'Content-Type': 'application/json'}

        #self.dlg.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)

    def llenarTabla(self):

        self.vaciarTabla()
        self.capaActiva = iface.activeLayer()
        nombre = self.pluginE.pluginM.ACA.traducirIdCapa( self.capaActiva.id())
        comboTemp = QtWidgets.QComboBox()
        
        if nombre == 'manzana':
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'predios.geom':
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'predios.num':
            self.listaAtributos = ['numExt']
            listaEtiquetas = ['Número Oficial']
        elif nombre == 'construcciones':
            self.listaAtributos = ['nom_volumen', 'num_niveles']
            listaEtiquetas = ['Nombre de Volumen', 'Número de Niveles']
        elif nombre == 'horizontales.geom':
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'horizontales.num':
            self.listaAtributos = ['num_ofi']
            listaEtiquetas = ['Número Oficial']
        elif nombre == 'verticales':
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'cves_verticales':
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'Area de Valor': #Areas de valor
            self.listaAtributos = ['valor', 'descripcion']
            listaEtiquetas = ['Valor', 'Descripcion']
        elif nombre == 'Zona Uno' or nombre == 'Zona Dos': #Zonas
            self.listaAtributos = ['descripcion']
            listaEtiquetas = ['Descripcion']
        elif nombre == 'Zona Dos': #Zonas
            self.listaAtributos = ['descripcion']
            listaEtiquetas = ['Descripcion']
        elif nombre == 'Predios': #Zonas
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'Colonias': #Codigo Postal
            self.listaAtributos = ['cve_col', 'id_tipo_asentamiento', 'descripcion']
            listaEtiquetas = ['Clave', 'Tipo de Asentamiento', 'Descripcion']
        elif nombre == 'Codigo Postal': #Colonia
            self.listaAtributos = ['cve_cp']
            listaEtiquetas = ['CP']
        elif nombre == 'Calles': #Calles
            self.listaAtributos = ['valor', 'longitud', 'id_cve_vialidad', 'tipo_vector_calle', 'calle']
            listaEtiquetas = ['Valor', 'Longitud', 'Clave vialidad', 'Tipo de Vector', 'Calle']
        elif nombre == 'Corredor de Valor': # Corredor de valor
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'Sectores': #Sector
            self.listaAtributos = ['clave']
            listaEtiquetas = ['Clave']
        elif nombre == 'Localidades': #Localidades
            self.listaAtributos = ['clave', 'nombre']
            listaEtiquetas = ['Clave', 'Nombre']
        elif nombre == 'Secciones': #Secciones
            self.listaAtributos = ['clave', 'nombre']
            listaEtiquetas = ['Clave', 'Nombre']
        elif nombre == 'Municipios': #Municipios
            self.listaAtributos = ['clave', 'nombre']
            listaEtiquetas = ['Clave', 'Nombre']
        elif nombre == 'Region Catastral': #Region Catastral
            self.listaAtributos = ['clave', 'nombre']
            listaEtiquetas = ['Clave', 'Nombre']
        elif nombre == 'Estado': #Estado
            self.listaAtributos = ['clave', 'nombre']
            listaEtiquetas = ['Clave', 'Nombre']
        else:
            self.listaAtributos = [f.name() for f in self.capaActiva.fields() if f.name() != 'id']
            listaEtiquetas = self.listaAtributos

        for x in range(0, len(listaEtiquetas)):
            self.dlg.tablaAtributos.insertRow(x)
            item = QtWidgets.QTableWidgetItem(str(listaEtiquetas[x]))
            self.dlg.tablaAtributos.setItem(x, 0 , item)#self.capaActual.getFeatures().attributes()[x])
            item.setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled )

        if nombre == 'construcciones': #Obtener tipos de construccion especial
            '''
            headers = {'Content-Type': 'application/json', 'Authorization' : self.pluginE.pluginM.UTI.obtenerToken()}

            respuesta = requests.get(self.pluginE.pluginM.CFG.urlTipoConst, headers = headers)
            print(respuesta)
            diccionarioConst = {}
            if respuesta.status_code == 200:
                for clave in respuesta.json():
                    comboTemp.addItem(str(clave['tipoConstruccion']), str(clave['id']) )
                    diccionarioConst[clave['id']] = str(clave['tipoConstruccion']) 
            else:
                self.pluginE.pluginM.UTI.mostrarAlerta("No se han podido cargar los tipos de construccion\nError de servidor", QMessageBox().Critical, "Cargar tipos de construccion especial")

            self.comboTipoConst = comboTemp
            comboTemp.currentIndexChanged.connect(self.cambiarTipoConstruccion)
            self.dlg.tablaAtributos.setCellWidget(1,1,comboTemp)
            '''
            pass

        elif nombre == 'Calles':
            comboTemp = QtWidgets.QComboBox()

            headers = {'Content-Type': 'application/json', 'Authorization' : self.pluginE.pluginM.UTI.obtenerToken()}

            respuesta = requests.get(self.pluginE.pluginM.CFG.urlTipoVialidad, headers = headers)
            comboTemp.addItem('Ninguno','NULL')
            if respuesta.status_code == 200:
                for resp in respuesta.json():
                    comboTemp.addItem(str(resp['cTipoVialidad']), str(resp['id']))

            else:
                print(respuesta.status_code)
                self.pluginE.pluginM.UTI.mostrarAlerta("No se han podido cargar los tipos de asentamiento\nError de servidor", QMessageBox().Critical, "Cargar tipos de vialidad")


            self.comboTipoVia = comboTemp
            self.dlg.tablaAtributos.setCellWidget(2,1,comboTemp)

            for x in self.capaActiva.getFeatures():  #Obtener ultimo feateure
                if x.id() > self.ultimo:
                    self.ultimo = x.id()

            nuevaCalle = self.capaActiva.getFeature(self.ultimo)

            longitud = nuevaCalle.geometry().length()
            item = QtWidgets.QTableWidgetItem(str(longitud))
            item.setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled )
            self.dlg.tablaAtributos.setItem(1, 1 , item)

        elif nombre == 'Colonias':
            comboTemp = QtWidgets.QComboBox()
            headers = {'Content-Type': 'application/json', 'Authorization' : self.pluginE.pluginM.UTI.obtenerToken()}
            respuesta = requests.get(self.pluginE.pluginM.CFG.urlTipoAsentamiento, headers = headers)
            comboTemp.addItem('Ninguno','NULL')
            if respuesta.status_code == 200:
                for resp in respuesta.json():
                    comboTemp.addItem(str(resp['descripcion']), str(resp['id']))

            else:
                print(respuesta.status_code)
                self.pluginE.pluginM.UTI.mostrarAlerta("No se han podido cargar los tipos de asentamiento\nError de servidor", QMessageBox().Critical, "Cargar tipos de asentamiento")


            self.comboTipoAs = comboTemp
            self.dlg.tablaAtributos.setCellWidget(1,1,comboTemp)

        elif nombre == 'Area de Valor':
            pass

        header = self.dlg.tablaAtributos.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)


############################################################################################    

    def mostrarTabla(self): #Mostrar tabla
        if self.posibleMostar and not self.dlg.isVisible():
            self.posibleMostar = False
            self.pluginE.pluginM.alternarModoDibujo()
            self.llenarTabla()
            self.dlg.show()        

############################################################################################

    def vaciarTabla(self): #Vaciar tabla

        self.dlg.tablaAtributos.clearContents()
        self.dlg.tablaAtributos.setRowCount(0)

        for row in range(0, self.dlg.tablaAtributos.rowCount()):        
            self.dlg.tablaAtributos.removeRow(row) 

##########################################################################################

    def confirmarFeature(self):
        #self.posibleMostar = True
        self.capaActiva = iface.activeLayer()
        self.capaActiva.setReadOnly(False)
        self.capaActiva.startEditing()
        banderaCompleta = True
        bandera2 = True
        nombreCapa = self.pluginE.pluginM.ACA.traducirIdCapa( self.capaActiva.id())
        campos = self.capaActiva.fields()   
        nombres = [campo.name() for campo in campos]

        if nombreCapa == 'predios.num':
            clavesActiva = [f['numExt'] for f in self.capaActiva.getFeatures()]
        elif nombreCapa == 'horizontales.num':
            clavesActiva = [f['num_ofi'] for f in self.capaActiva.getFeatures()]
        else:
            clavesActiva = [f['clave'] for f in self.capaActiva.getFeatures() if 'clave' in nombres]


        for x in self.capaActiva.getFeatures():  #Obtener ultimo feateure
            if x.id() > self.ultimo:
                self.ultimo = x.id()

        self.listaIndex = []

        for nombre in nombres:
            
            if nombre in self.listaAtributos:
                self.listaIndex.append(campos.lookupField(nombre))
        
        feat = self.capaActiva.getFeature(self.ultimo)
        

        # validar las claves invalidas
        sector = ''

        if nombreCapa == 'manzana' or nombreCapa == 'predios.geom':
            # cargar la capa de sectores
            sectorCapa = QgsProject.instance().mapLayer(QSettings().value('xSector'))
            manzanaCapa = QgsProject.instance().mapLayer(QSettings().value('xManzana'))

            # validacion para la capa en edicion
            if not sectorCapa:
                # no tiene valor, es momento de pintar la capa
                self.pluginE.pluginM.ACA.pintarCapasReferencia('Sectores', None, False)
                sectorCapa = QgsProject.instance().mapLayer(QSettings().value('xSector'))

            # obtener la clave del sector donde esta contenida la manzana
            fTemp = sectorCapa.getFeatures()
            # obtenemos la primer geometria de la maanzana
            if list(manzanaCapa.getFeatures()) == []:
                bandera2 = False
            else:
                fMAnza = list(manzanaCapa.getFeatures())[0]
           
            # se obtienen todos las geometrias con las que coline la manzana
                lista = []
                for f in fTemp:
                    valor = fMAnza.geometry().intersects(f.geometry())
                    if valor > 0:
                        l = {}
                        l['v'] = valor
                        l['c'] = f['clave']

                        lista.append(l)

            # obtener el registro con el valor mas grande para saber la clave del sector
                if len(lista) > 0:
                    maxim = max(lista, key=lambda x:x['v'])
                    sector = maxim['c']

        #.....Manzana....#
        if nombreCapa == 'manzana':
            texto = ""
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 3: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaCompleta = False
            else: #Cuando no es numerico
                banderaCompleta = False

            if banderaCompleta:
                # consulta para verificacion de clave MANZANA
                mpio = QSettings().value("cveMpio")

                payload = {}
                payload['clave'] = texto
                payload['claveFiltro'] = mpio + '-' + sector
                payload['tipo'] = 'MANZANA'
                respuesta = self.consumeWSGeneral(self.pluginE.pluginM.CFG.url_validaClaves, payload)
                print(respuesta)
                if not respuesta:
                    self.capaActiva.commitChanges()
                    return

                if not respuesta['uso']:
                    self.capaActiva.commitChanges()
                    self.pluginE.pluginM.UTI.mostrarAlerta("La clave '" + texto+ "' se encuentra inactiva, no se puede usar", QMessageBox().Critical, 'Error de entrada')
                    return 
            
            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por exactamente 3 números', QMessageBox().Critical, 'Error de entrada')

            if texto in clavesActiva:
                self.pluginE.pluginM.UTI.mostrarAlerta(
                    "La clave '" + texto + "' ya se encuentra en uso", QMessageBox().Critical,
                    'Error de entrada')
                return

        #.....predios geom....#
        elif nombreCapa == 'predios.geom':
            texto = "Nada"
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 2: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaCompleta = False
                    bandera2 = False
            else: #Cuando no es numerico
                banderaCompleta = False
                bandera2 = False

            if banderaCompleta:

                manzana = ''
                # obtener la clave de la manzana donde esta contenido el predio
                fTemp = manzanaCapa.getFeatures()
                # obtenemos la geometria seleccionada de la capa activa
                fPredio = feat
                # se obtienen todos las geometrias con las que coline el predio
                lista = []
                for f in fTemp:
                    valor = fPredio.geometry().intersects(f.geometry())
                    if valor > 0:
                        l = {}
                        l['v'] = valor
                        l['c'] = f['clave']

                        lista.append(l)

                # obtener el registro con el valor mas grande para saber la clave de la manzana
                if len(lista) > 0:
                    maxim = max(lista, key=lambda x:x['v'])
                    manzana = maxim['c']

                # consulta para verificacion de clave MANZANA
                mpio = QSettings().value("cveMpio")

                payload = {}
                payload['clave'] = texto
                payload['claveFiltro'] = mpio + '-' + sector + '-' + manzana
                payload['tipo'] = 'PREDIO'
                respuesta = self.consumeWSGeneral(self.pluginE.pluginM.CFG.url_validaClaves, payload)
                print(respuesta)
                if not respuesta:
                    self.capaActiva.commitChanges()
                    return

                if not respuesta['uso']:
                    self.capaActiva.commitChanges()
                    self.pluginE.pluginM.UTI.mostrarAlerta("La clave '" + texto+ "' se encuentra inactiva, no se puede usar", QMessageBox().Critical, 'Error de entrada')
                    return 
            
            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por exactamente 2 números', QMessageBox().Critical, 'Error de entrada')

            if texto in clavesActiva:
                self.pluginE.pluginM.UTI.mostrarAlerta(
                    "La clave '" + texto + "' ya se encuentra en uso", QMessageBox().Critical,
                    'Error de entrada')
                return

        #.....predios geom....#
        elif nombreCapa == 'predios.num':
            texto = "Nada"
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False

            lenText = len(texto.strip())

            if lenText < 21 and lenText > 0: #Validacion de longitud
                feat['numExt'] = texto
            else:
                banderaCompleta = False

            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('El número oficial no debe exceder los 20 caracteres', QMessageBox().Critical, 'Error de entrada')
        
        #.....predios geom....#
        elif nombreCapa == 'horizontales.geom':
            texto = "Nada"
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 6: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaCompleta = False
            else: #Cuando no es numerico
                banderaCompleta = False

            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por exactamente 6 números', QMessageBox().Critical, 'Error de entrada')    

            if texto in clavesActiva:
                self.pluginE.pluginM.UTI.mostrarAlerta(
                    "La clave '" + texto + "' ya se encuentra en uso", QMessageBox().Critical,
                    'Error de entrada')
                return

        #.....predios geom....#
        elif nombreCapa == 'horizontales.num':
            texto = "Nada"
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False

            lenText = len(texto.strip())
            if lenText < 21 and lenText > 0: #Validacion de longitud
                feat['num_ofi'] = texto
            else:
                banderaCompleta = False
            
            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('El número oficial no debe exceder los 20 caracteres', QMessageBox().Critical, 'Error de entrada')

        #.....verticales geom....#
        elif nombreCapa == 'verticales':
            texto = "Nada"
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 2: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaCompleta = False
            else: #Cuando no es numerico
                banderaCompleta = False

            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por exactamente 2 números', QMessageBox().Critical, 'Error de entrada')

            if texto in clavesActiva:
                self.pluginE.pluginM.UTI.mostrarAlerta(
                    "La clave '" + texto + "' ya se encuentra en uso", QMessageBox().Critical,
                    'Error de entrada')
                return

        #.....clvaees verticales....#
        elif nombreCapa == 'cves_verticales':
            texto = "Nada"
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 4: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaCompleta = False
            else: #Cuando no es numerico
                banderaCompleta = False
            
            if not banderaCompleta: #Mensaje de error
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por exactamente 4 números', QMessageBox().Critical, 'Error de entrada')


        elif nombreCapa == 'construcciones': #Con Construcciones

            bandera1 = True
            comboIndex1 = self.comboTipoConst.currentIndex()  #Combo de tipo de construccion
              #Combo de construccion especial
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
                if len(texto) > 0 and len(texto) <=3:
                    feat['nom_volumen'] = texto
                else:
                    bandera1 = False
            except:
                bandera1 = False

            if not bandera1:
                self.pluginE.pluginM.UTI.mostrarAlerta('El nombre de volumen no debe exceder los 3 caracteres', QMessageBox().Critical, 'Error de entrada')
            
            bandera2 = True

            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
                
                if len(texto) > 0 and int(texto) < 999 and self.pluginE.pluginM.UTI.esEntero(texto):
                    feat['num_niveles'] = texto
                    
                else:
                    bandera2 = False
            except:
                bandera2 = False

            if not bandera2:
                self.pluginE.pluginM.UTI.mostrarAlerta('El número de niveles debe ser numérico y no exceder 999', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = bandera1 and bandera2
                
        #----------------------Area de valorZona------------------#
        elif nombreCapa == 'Area de Valor':

            texto = "Nada"

            banderaValor = True

            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaValor = False
            if self.pluginE.pluginM.UTI.esFloat(texto): #Cuando es entero
                if len(texto) < 12: #Validacion de longitud
                    feat['valor'] = float(texto)
                else:
                    banderaValor = False
            else: #Cuando no es numerico
                banderaValor = False
            
            banderaDesc = True

            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
            except: #Error al obtenre texto
                banderaDesc = False
            if len(texto) <= 256: #Validacion de longitud
                feat['descripcion'] = texto
            else:
                banderaDesc = False


            if not banderaValor:
                self.pluginE.pluginM.UTI.mostrarAlerta('El valor debe ser un número decimal cuya longitud de texto no exceda 12 caracteres', QMessageBox().Critical, 'Error de entrada')

            if not banderaDesc:
                self.pluginE.pluginM.UTI.mostrarAlerta('La descripcion no debe exceder 256 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaValor and banderaDesc

            if banderaCompleta:
                indexCveVus = self.comboCveVus.currentIndex()
                feat['cve_vus'] = self.comboCveVus.itemData(indexCveVus)
        
        #----------------------Zona uno------------------#
        elif nombreCapa == 'Zona Uno':

            texto = "Nada"

            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if len(texto) <= 50: #Validacion de longitud
                feat['descripcion'] = texto
            else:
                banderaCompleta = False

            
            if not banderaCompleta:
                self.pluginE.pluginM.UTI.mostrarAlerta('La descripcion no debe exceder 50 caracteres', QMessageBox().Critical, 'Error de entrada')

        #----------------------Zona dos------------------#
        elif nombreCapa == 'Zona Dos':

            texto = "Nada"

            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if len(texto) <= 50: #Validacion de longitud
                feat['descripcion'] = texto
            else:
                banderaCompleta = False

            
            if not banderaCompleta:
                self.pluginE.pluginM.UTI.mostrarAlerta('La descripcion no debe exceder 50 caracteres', QMessageBox().Critical, 'Error de entrada')

        #----------------------Codigo Postal------------------#
        elif nombreCapa == 'Codigo Postal':

            texto = "Nada"

            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaCompleta = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 5: #Validacion de longitud
                    feat['cve_cp'] = texto
                else:
                    banderaCompleta = False
            else: #Cuando no es numerico
                banderaCompleta = False
            
            if not banderaCompleta:
                self.pluginE.pluginM.UTI.mostrarAlerta('El codigo postal debe estar compuesto por 5 números', QMessageBox().Critical, 'Error de entrada')

        #----------------------Colonias------------------#
        elif nombreCapa == 'Colonias':

            texto = "Nada"

            banderaClave = True
            banderaDesc = True

            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if len(texto) == 4: #Validacion de longitud
                feat['cve_col'] = texto
            else:
                banderaClave = False

            
            try:
                texto = self.dlg.tablaAtributos.item(2, 1).text()
            except: #Error al obtenre texto
                banderaDesc = False
            if len(texto) <= 64: #Validacion de longitud
                feat['descripcion'] = texto
            else:
                banderaDesc = False

            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud de la clave debe ser de 4 caracteres', QMessageBox().Critical, 'Error de entrada')

            if not banderaDesc:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud de la descripcion no debe exceder 64 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaClave and banderaDesc

            if banderaCompleta:
                indexComboAs = self.comboTipoAs.currentIndex()
                feat['id_tipo_asentamiento'] = self.comboTipoAs.itemData(indexComboAs)

         #----------------------Calles------------------#
        elif nombreCapa == 'Calles':

            texto = "Nada"

            banderaTipo = True
            banderaCalle = True
            banderaValor = True

            #Comparar la clave
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaValor = False

            if self.pluginE.pluginM.UTI.esFloat(texto): #Cuando es entero
                if len(texto) < 12: #Validacion de longitud
                    #print(float(texto))
                    feat['valor'] = float(texto)
                    #print(feat['valor'])
                else:
                    banderaValor = False
            else: #Cuando no es numerico
                banderaValor = False


            try:
                texto = self.dlg.tablaAtributos.item(4, 1).text()
            except: #Error al obtenre texto
                banderaCalle = False
            if len(texto) <= 256: #Validacion de longitud
                feat['calle'] = texto
            else:
                banderaCalle = False

            
            try:
                texto = self.dlg.tablaAtributos.item(3, 1).text()
            except: #Error al obtenre texto
                banderaTipo = False
            if len(texto) <= 64: #Validacion de longitud
                feat['tipo_vector_calle'] = texto
            else:
                banderaTipo = False


            if not banderaValor:
                self.pluginE.pluginM.UTI.mostrarAlerta('El valor debe ser decimal y no exceder los 12 caracteres de longitud', QMessageBox().Critical, 'Error de entrada')

            if not banderaCalle:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud de la calle no debe exceder 256 caracteres', QMessageBox().Critical, 'Error de entrada')

            if not banderaTipo:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud del tipo de vector no debe exceder 64 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaValor and banderaTipo and banderaTipo

            if banderaCompleta:
                indexComboVia = self.comboTipoVia.currentIndex()
                feat['id_cve_vialidad'] = self.comboTipoVia.itemData(indexComboVia)
                feat['c_tipo_vialidad'] = self.comboTipoVia.currentText()
                feat['longitud'] = float(self.dlg.tablaAtributos.item(1, 1).text())

        #----------------------Sectores------------------#
        elif nombreCapa == 'Sectores':

            texto = "Nada"

            banderaClave = True
            banderaNom = True

            #Comparar la clave
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 2: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaClave = False
            else: #Cuando no es numerico
                banderaClave = False

            if banderaClave:
                # consulta para verificacion de clave SECTOR
                mpio = QSettings().value("cveMpio")

                payload = {}
                payload['clave'] = texto
                payload['claveFiltro'] = mpio
                payload['tipo'] = 'SECTOR'
                print(payload, self.pluginE.pluginM.CFG.url_validaClaves)
                respuesta = self.consumeWSGeneral(self.pluginE.pluginM.CFG.url_validaClaves, payload)
                print(respuesta)
                if not respuesta:
                    return

                if not respuesta['uso']:
                    self.pluginE.pluginM.UTI.mostrarAlerta("La clave '" + texto+ "' se encuentra inactiva, no se puede usar", QMessageBox().Critical, 'Error de entrada')
                    return
            
            #Banderas
            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por 2 números', QMessageBox().Critical, 'Error de entrada')

            if texto in clavesActiva:
                self.pluginE.pluginM.UTI.mostrarAlerta(
                    "La clave '" + texto + "' ya se encuentra en uso", QMessageBox().Critical,
                    'Error de entrada')
                return


            banderaCompleta = banderaClave 

        #----------------------Codigo Postal------------------#
        elif nombreCapa == 'Localidades':

            texto = "Nada"

            banderaClave = True
            banderaNom = True

            #Comparar la clave
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 4: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaClave = False
            else: #Cuando no es numerico
                banderaClave = False
            
            #Comparar el nombre
            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
            except: #Error al obtenre texto
                banderaNom = False
            if len(texto) <= 256: #Validacion de longitud
                feat['nombre'] = texto
            else:
                banderaNom = False

            #Banderas
            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por 4 números', QMessageBox().Critical, 'Error de entrada')

            if not banderaNom:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud del nombre no debe exceder 256 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaClave and banderaNom

        #----------------------Codigo Postal------------------#
        elif nombreCapa == 'Secciones':

            texto = "Nada"

            banderaClave = True
            banderaNom = True

            #Comparar la clave
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 2: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaClave = False
            else: #Cuando no es numerico
                banderaClave = False
            
            #Comparar el nombre
            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
            except: #Error al obtenre texto
                banderaNom = False
            if len(texto) <= 64: #Validacion de longitud
                feat['nombre'] = texto
            else:
                banderaNom = False

            #Banderas
            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por 2 números', QMessageBox().Critical, 'Error de entrada')

            if not banderaNom:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud del nombre no debe exceder 64 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaClave and banderaNom

        #----------------------Codigo Postal------------------#
        elif nombreCapa == 'Municipios':

            texto = "Nada"

            banderaClave = True
            banderaNom = True

            #Comparar la clave
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 3: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaClave = False
            else: #Cuando no es numerico
                banderaClave = False
            
            #Comparar el nombre
            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
            except: #Error al obtenre texto
                banderaNom = False
            if len(texto) <= 256: #Validacion de longitud
                feat['nombre'] = texto
            else:
                banderaNom = False

            #Banderas
            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por 3 números', QMessageBox().Critical, 'Error de entrada')

            if not banderaNom:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud del nombre no debe exceder 256 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaClave and banderaNom

        #----------------------Codigo Postal------------------#
        elif nombreCapa == 'Region Catastral':

            texto = "Nada"

            banderaClave = True
            banderaNom = True

            #Comparar la clave
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 3: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaClave = False
            else: #Cuando no es numerico
                banderaClave = False
            
            #Comparar el nombre
            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
            except: #Error al obtenre texto
                banderaNom = False
            if len(texto) <= 64: #Validacion de longitud
                feat['nombre'] = texto
            else:
                banderaNom = False

            #Banderas
            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por 3 números', QMessageBox().Critical, 'Error de entrada')

            if not banderaNom:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud del nombre no debe exceder 64 caracteres', QMessageBox().Critical, 'Error de entrada')

            banderaCompleta = banderaClave and banderaNom

        #----------------------Codigo Postal------------------#
        elif nombreCapa == 'Estado':

            texto = "Nada"

            banderaClave = True
            banderaNom = True

            #Comparar la clave
            
            try:
                texto = self.dlg.tablaAtributos.item(0, 1).text()
            except: #Error al obtenre texto
                banderaClave = False
            if self.pluginE.pluginM.UTI.esEntero(texto): #Cuando es entero
                if len(texto) == 2: #Validacion de longitud
                    feat['clave'] = texto
                else:
                    banderaClave = False
            else: #Cuando no es numerico
                banderaClave = False
            
            #Comparar el nombre
            try:
                texto = self.dlg.tablaAtributos.item(1, 1).text()
            except: #Error al obtenre texto
                banderaNom = False
            if len(texto) <= 64: #Validacion de longitud
                feat['nombre'] = texto
                
            else:
                banderaNom = False


            banderaCompleta = banderaClave and banderaNom

            #Banderas
            if not banderaClave:
                self.pluginE.pluginM.UTI.mostrarAlerta('La clave debe estar compuesta por 2 números', QMessageBox().Critical, 'Error de entrada')

            if not banderaNom:
                self.pluginE.pluginM.UTI.mostrarAlerta('La longitud del nombre no debe exceder 64 caracteres', QMessageBox().Critical, 'Error de entrada')
        # ----------------------Capas custom------------------#
        else:
            for i in range( self.dlg.tablaAtributos.rowCount()):
                nomAtrib = self.dlg.tablaAtributos.item(i, 0).text()
                valAtrib = self.dlg.tablaAtributos.item(i, 1).text() if self.dlg.tablaAtributos.item(i, 1) is not None else "None"
                feat[nomAtrib] = valAtrib
            banderaCompleta = True

        self.capaActiva.setReadOnly(True)
        if banderaCompleta:
            
            self.capaActiva.updateFeature(feat)
            self.posibleCerrar = True
            self.posibleMostar = True
            self.dlg.close()
            self.posibleCerrar = False
            self.capaActiva.triggerRepaint()
            self.capaActiva.commitChanges()

            # instrucciones para detectar el ultimo feature agregad a la capa
            feature = list(self.capaActiva.getFeatures())[self.capaActiva.featureCount() - 1]
            QSettings().setValue('ultIdAgregado', int(feature.id()))

##################################################################################################

    def cancelarFeature(self):

        self.capaActiva = iface.activeLayer()
        self.capaActiva.startEditing()

        for x in self.capaActiva.getFeatures():
            if x.id() > self.ultimo:
                self.ultimo = x.id()

        self.capaActiva.dataProvider().deleteFeatures([self.ultimo])
            
        self.posibleCerrar = True
        self.posibleMostar = True
        self.dlg.close()
        self.posibleCerrar = False
        self.capaActiva.triggerRepaint()
        self.capaActiva.commitChanges()

########################################################################################################################

    def cambiarTipoConstruccion(self):

        index = self.comboTipoConst.currentIndex()
        #self.dlg.tablaAtributos.removeRow(2)

        if index == 0:
            #self.dlg.tablaAtributos.insertRow(2)
            item = QtWidgets.QTableWidgetItem('Número de niveles')
            self.dlg.tablaAtributos.setItem(2, 0 , item)#self.capaActual.getFeatures().attributes()[x])
            item.setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled )
            self.dlg.tablaAtributos.removeCellWidget(2,1)
        else:
            #self.dlg.tablaAtributos.insertRow(2)
            item = QtWidgets.QTableWidgetItem('Const. Especial')
            self.dlg.tablaAtributos.setItem(2, 0 , item)#self.capaActual.getFeatures().attributes()[x])
            item.setFlags( QtCore.Qt.ItemIsSelectable |  QtCore.Qt.ItemIsEnabled )

            comboTemp = QtWidgets.QComboBox()
            headers = {'Content-Type': 'application/json', 'Authorization' : self.pluginE.pluginM.UTI.obtenerToken()}

            respuesta = requests.get(self.pluginE.pluginM.CFG.urlTipoConstEsp, headers = headers)
            
            diccionarioConst = {}
            if respuesta.status_code == 200:
                for clave in respuesta.json():
                    comboTemp.addItem(str(clave['cveConstEsp']) + " - " + clave['descripcion'], str(clave['cveConstEsp']) )
                    diccionarioConst[clave['cveConstEsp']] = str(clave['cveConstEsp']) + " - " + clave['descripcion']
            else:
                self.pluginE.pluginM.UTI.mostrarAlerta("No se han podido cargar los tipos de construccion especial\nError de servidor", QMessageBox().Critical, "Cargar tipos de construccion especial")

            self.comboConstEsp = comboTemp

            self.dlg.tablaAtributos.setCellWidget(2,1,self.comboConstEsp)

##################################################################################################
# --- S E R V I C I O S   W E B  ---

    # POST 
    def consumeWSGeneral(self, url_cons = "", payload = {}):

        url = url_cons
        data = ""

        # envio - el objeto de tipo dict, es el json que se va a guardar
        # se debe hacer la conversion para que sea aceptado por el servicio web
        jsonEnv = json.dumps(payload)

        try:
            # header para obtener el token
            self.headers['Authorization'] = self.pluginE.pluginM.UTI.obtenerToken()

            # ejemplo con post, url, header y body o datos a enviar
            response = requests.post(url, headers = self.headers, data = jsonEnv)

        except requests.exceptions.RequestException as e:
            self.pluginE.pluginM.UTI.mostrarAlerta("Error de servidor, 'consumeWSGeneral()", QMessageBox().Critical, "Error de servidor")
            print("consumeWSGeneral() '" + str(e) + "'")
            return None

        if response.status_code == 200 or response.status_code == 201:
            data = response.content

        elif response.status_code == 403:
            self.pluginE.pluginM.UTI.mostrarAlerta('Sin Permisos para ejecutar la accion', QMessageBox().Critical, "Usuarios")
            return None
           
        else:
            print(response.text)
            self.pluginE.pluginM.UTI.mostrarAlerta('Error en peticion "consumeWSGeneral()"', QMessageBox().Critical, "Error de servidor")
            return None

        return json.loads(data)

    # --- S E R V I C I O S   W E B   CIERRA ---