# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'actualizacioncatastralv2_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_actualizacioncatastralv2DockWidgetBase(object):
    def setupUi(self, actualizacioncatastralv2DockWidgetBase):
        actualizacioncatastralv2DockWidgetBase.setObjectName("actualizacioncatastralv2DockWidgetBase")
        actualizacioncatastralv2DockWidgetBase.resize(386, 733)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboLocalidad = QtWidgets.QComboBox(self.tab)
        self.comboLocalidad.setGeometry(QtCore.QRect(130, 50, 171, 21))
        self.comboLocalidad.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.comboLocalidad.setObjectName("comboLocalidad")
        self.comboSector = QtWidgets.QComboBox(self.tab)
        self.comboSector.setGeometry(QtCore.QRect(130, 90, 171, 21))
        self.comboSector.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.comboSector.setObjectName("comboSector")
        self.comboManzana = QtWidgets.QComboBox(self.tab)
        self.comboManzana.setGeometry(QtCore.QRect(130, 130, 171, 21))
        self.comboManzana.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.comboManzana.setObjectName("comboManzana")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 50, 111, 21))
        self.label.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 111, 21))
        self.label_2.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(0, 130, 111, 21))
        self.label_3.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.label_3.setObjectName("label_3")
        self.botonCargar = QtWidgets.QPushButton(self.tab)
        self.botonCargar.setGeometry(QtCore.QRect(60, 170, 241, 26))
        self.botonCargar.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.botonCargar.setObjectName("botonCargar")
        self.labelEdicion = QtWidgets.QLabel(self.tab)
        self.labelEdicion.setGeometry(QtCore.QRect(0, 330, 351, 20))
        self.labelEdicion.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelEdicion.setObjectName("labelEdicion")
        self.labelTituloEditar = QtWidgets.QLabel(self.tab)
        self.labelTituloEditar.setGeometry(QtCore.QRect(0, 360, 141, 21))
        self.labelTituloEditar.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelTituloEditar.setObjectName("labelTituloEditar")
        self.tablaEdicion = QtWidgets.QTableWidget(self.tab)
        self.tablaEdicion.setGeometry(QtCore.QRect(40, 420, 281, 191))
        self.tablaEdicion.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.tablaEdicion.setObjectName("tablaEdicion")
        self.tablaEdicion.setColumnCount(2)
        self.tablaEdicion.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEdicion.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEdicion.setHorizontalHeaderItem(1, item)
        self.botonEditar = QtWidgets.QPushButton(self.tab)
        self.botonEditar.setGeometry(QtCore.QRect(60, 630, 241, 26))
        self.botonEditar.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.botonEditar.setObjectName("botonEditar")
        self.labelCapaEdicion = QtWidgets.QLabel(self.tab)
        self.labelCapaEdicion.setGeometry(QtCore.QRect(150, 360, 211, 20))
        self.labelCapaEdicion.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelCapaEdicion.setObjectName("labelCapaEdicion")
        self.labelStatusEdicion = QtWidgets.QLabel(self.tab)
        self.labelStatusEdicion.setGeometry(QtCore.QRect(0, 390, 361, 21))
        self.labelStatusEdicion.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelStatusEdicion.setObjectName("labelStatusEdicion")
        self.labelEdicion_2 = QtWidgets.QLabel(self.tab)
        self.labelEdicion_2.setGeometry(QtCore.QRect(0, 10, 361, 20))
        self.labelEdicion_2.setStyleSheet("font: 25 7pt \"Bahnschrift Light\";")
        self.labelEdicion_2.setObjectName("labelEdicion_2")
        self.comboCapaReferencia = QtWidgets.QComboBox(self.tab)
        self.comboCapaReferencia.setGeometry(QtCore.QRect(70, 250, 231, 22))
        self.comboCapaReferencia.setObjectName("comboCapaReferencia")
        self.labelEdicion_3 = QtWidgets.QLabel(self.tab)
        self.labelEdicion_3.setGeometry(QtCore.QRect(0, 220, 361, 20))
        self.labelEdicion_3.setStyleSheet("font: 25 7pt \"Bahnschrift Light\";")
        self.labelEdicion_3.setObjectName("labelEdicion_3")
        self.botonCargarReferencia = QtWidgets.QPushButton(self.tab)
        self.botonCargarReferencia.setGeometry(QtCore.QRect(64, 290, 241, 26))
        self.botonCargarReferencia.setObjectName("botonCargarReferencia")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.labeCapalEdicionRef = QtWidgets.QLabel(self.tab_2)
        self.labeCapalEdicionRef.setGeometry(QtCore.QRect(170, 50, 191, 20))
        self.labeCapalEdicionRef.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labeCapalEdicionRef.setObjectName("labeCapalEdicionRef")
        self.labelTituloEditar_2 = QtWidgets.QLabel(self.tab_2)
        self.labelTituloEditar_2.setGeometry(QtCore.QRect(0, 50, 141, 21))
        self.labelTituloEditar_2.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelTituloEditar_2.setObjectName("labelTituloEditar_2")
        self.labelStatusEdicionRef = QtWidgets.QLabel(self.tab_2)
        self.labelStatusEdicionRef.setGeometry(QtCore.QRect(0, 80, 361, 21))
        self.labelStatusEdicionRef.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelStatusEdicionRef.setObjectName("labelStatusEdicionRef")
        self.botonEditarRef = QtWidgets.QPushButton(self.tab_2)
        self.botonEditarRef.setGeometry(QtCore.QRect(70, 320, 241, 26))
        self.botonEditarRef.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.botonEditarRef.setObjectName("botonEditarRef")
        self.labelEdicion_4 = QtWidgets.QLabel(self.tab_2)
        self.labelEdicion_4.setGeometry(QtCore.QRect(0, 20, 361, 20))
        self.labelEdicion_4.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.labelEdicion_4.setObjectName("labelEdicion_4")
        self.tablaEdicionRef = QtWidgets.QTableWidget(self.tab_2)
        self.tablaEdicionRef.setGeometry(QtCore.QRect(30, 110, 301, 191))
        self.tablaEdicionRef.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";")
        self.tablaEdicionRef.setObjectName("tablaEdicionRef")
        self.tablaEdicionRef.setColumnCount(2)
        self.tablaEdicionRef.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEdicionRef.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaEdicionRef.setHorizontalHeaderItem(1, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        actualizacioncatastralv2DockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(actualizacioncatastralv2DockWidgetBase)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(actualizacioncatastralv2DockWidgetBase)

    def retranslateUi(self, actualizacioncatastralv2DockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        actualizacioncatastralv2DockWidgetBase.setWindowTitle(_translate("actualizacioncatastralv2DockWidgetBase", "actualizacioncatastralv2"))
        self.label.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Localidad</span></p></body></html>"))
        self.label_2.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Sector</span></p></body></html>"))
        self.label_3.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Manzana</span></p></body></html>"))
        self.botonCargar.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Cargar manzana"))
        self.labelEdicion.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">EDICION</span></p></body></html>"))
        self.labelTituloEditar.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Capa a editar</span></p></body></html>"))
        item = self.tablaEdicion.horizontalHeaderItem(0)
        item.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Atributo"))
        item = self.tablaEdicion.horizontalHeaderItem(1)
        item.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Valor"))
        self.botonEditar.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Actualizar"))
        self.labelCapaEdicion.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">----</span></p></body></html>"))
        self.labelStatusEdicion.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">---</span></p></body></html>"))
        self.labelEdicion_2.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt; font-weight:600;\">ACTUALIZACION CARTOGRAFICA DE MANZANA</span></p></body></html>"))
        self.labelEdicion_3.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">CAPAS DE REFERENCIA</span></p></body></html>"))
        self.botonCargarReferencia.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Cargar capa de referencia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("actualizacioncatastralv2DockWidgetBase", "Actualizacion Cartografica de Manzana"))
        self.labeCapalEdicionRef.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">----</span></p></body></html>"))
        self.labelTituloEditar_2.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Capa a editar</span></p></body></html>"))
        self.labelStatusEdicionRef.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">---</span></p></body></html>"))
        self.botonEditarRef.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Actualizar"))
        self.labelEdicion_4.setText(_translate("actualizacioncatastralv2DockWidgetBase", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">EDICION DE CAPAS DE REFERENCIA</span></p></body></html>"))
        item = self.tablaEdicionRef.horizontalHeaderItem(0)
        item.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Atributo"))
        item = self.tablaEdicionRef.horizontalHeaderItem(1)
        item.setText(_translate("actualizacioncatastralv2DockWidgetBase", "Valor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("actualizacioncatastralv2DockWidgetBase", "Capas de Referencia"))

