# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1030, 968)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(674, 590))
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setMinimumSize(QtCore.QSize(569, 43))
        self.widget_6.setMaximumSize(QtCore.QSize(569, 43))
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbCveCata = QtWidgets.QLabel(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbCveCata.setFont(font)
        self.lbCveCata.setObjectName("lbCveCata")
        self.gridLayout_5.addWidget(self.lbCveCata, 0, 0, 1, 1)
        self.cmbCondo = QtWidgets.QComboBox(self.widget_6)
        self.cmbCondo.setMinimumSize(QtCore.QSize(100, 27))
        self.cmbCondo.setMaximumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.cmbCondo.setFont(font)
        self.cmbCondo.setObjectName("cmbCondo")
        self.gridLayout_5.addWidget(self.cmbCondo, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_6, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(75, 50))
        self.pushButton_2.setMaximumSize(QtCore.QSize(75, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_4)
        self.tabWidget.setObjectName("tabWidget")
        self.tUbicacion = QtWidgets.QWidget()
        self.tUbicacion.setObjectName("tUbicacion")
        self.gridLayout = QtWidgets.QGridLayout(self.tUbicacion)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tUbicacion)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 641, 702))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_7.setMinimumSize(QtCore.QSize(400, 70))
        self.widget_7.setMaximumSize(QtCore.QSize(400, 70))
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lbPredio = QtWidgets.QLabel(self.widget_7)
        self.lbPredio.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbPredio.setFont(font)
        self.lbPredio.setStyleSheet("color:#ff0000")
        self.lbPredio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbPredio.setObjectName("lbPredio")
        self.gridLayout_6.addWidget(self.lbPredio, 2, 7, 1, 1)
        self.label_0 = QtWidgets.QLabel(self.widget_7)
        self.label_0.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_0.setObjectName("label_0")
        self.gridLayout_6.addWidget(self.label_0, 0, 0, 1, 8)
        self.lbEdo = QtWidgets.QLabel(self.widget_7)
        self.lbEdo.setMinimumSize(QtCore.QSize(35, 0))
        self.lbEdo.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbEdo.setFont(font)
        self.lbEdo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbEdo.setObjectName("lbEdo")
        self.gridLayout_6.addWidget(self.lbEdo, 2, 0, 1, 1)
        self.lbLoc = QtWidgets.QLabel(self.widget_7)
        self.lbLoc.setMinimumSize(QtCore.QSize(45, 0))
        self.lbLoc.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbLoc.setFont(font)
        self.lbLoc.setAlignment(QtCore.Qt.AlignCenter)
        self.lbLoc.setObjectName("lbLoc")
        self.gridLayout_6.addWidget(self.lbLoc, 2, 4, 1, 1)
        self.label_d = QtWidgets.QLabel(self.widget_7)
        self.label_d.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label_d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d.setObjectName("label_d")
        self.gridLayout_6.addWidget(self.label_d, 1, 3, 1, 1)
        self.label_g = QtWidgets.QLabel(self.widget_7)
        self.label_g.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_g.setAlignment(QtCore.Qt.AlignCenter)
        self.label_g.setObjectName("label_g")
        self.gridLayout_6.addWidget(self.label_g, 1, 6, 1, 1)
        self.label_e = QtWidgets.QLabel(self.widget_7)
        self.label_e.setMinimumSize(QtCore.QSize(45, 0))
        self.label_e.setMaximumSize(QtCore.QSize(45, 16777215))
        self.label_e.setStyleSheet("text-align: center")
        self.label_e.setAlignment(QtCore.Qt.AlignCenter)
        self.label_e.setObjectName("label_e")
        self.gridLayout_6.addWidget(self.label_e, 1, 4, 1, 1)
        self.lbRegCat = QtWidgets.QLabel(self.widget_7)
        self.lbRegCat.setMinimumSize(QtCore.QSize(50, 0))
        self.lbRegCat.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbRegCat.setFont(font)
        self.lbRegCat.setAlignment(QtCore.Qt.AlignCenter)
        self.lbRegCat.setObjectName("lbRegCat")
        self.gridLayout_6.addWidget(self.lbRegCat, 2, 1, 1, 1)
        self.label_f = QtWidgets.QLabel(self.widget_7)
        self.label_f.setMinimumSize(QtCore.QSize(35, 0))
        self.label_f.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label_f.setAlignment(QtCore.Qt.AlignCenter)
        self.label_f.setObjectName("label_f")
        self.gridLayout_6.addWidget(self.label_f, 1, 5, 1, 1)
        self.label_a = QtWidgets.QLabel(self.widget_7)
        self.label_a.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_a.setAlignment(QtCore.Qt.AlignCenter)
        self.label_a.setObjectName("label_a")
        self.gridLayout_6.addWidget(self.label_a, 1, 0, 1, 1)
        self.lbSecc = QtWidgets.QLabel(self.widget_7)
        self.lbSecc.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbSecc.setFont(font)
        self.lbSecc.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSecc.setObjectName("lbSecc")
        self.gridLayout_6.addWidget(self.lbSecc, 2, 3, 1, 1)
        self.lbMpio = QtWidgets.QLabel(self.widget_7)
        self.lbMpio.setMinimumSize(QtCore.QSize(35, 0))
        self.lbMpio.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbMpio.setFont(font)
        self.lbMpio.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMpio.setObjectName("lbMpio")
        self.gridLayout_6.addWidget(self.lbMpio, 2, 2, 1, 1)
        self.lbMza = QtWidgets.QLabel(self.widget_7)
        self.lbMza.setMaximumSize(QtCore.QSize(40, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbMza.setFont(font)
        self.lbMza.setStyleSheet("color:#ff0000")
        self.lbMza.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMza.setObjectName("lbMza")
        self.gridLayout_6.addWidget(self.lbMza, 2, 6, 1, 1)
        self.lbSec = QtWidgets.QLabel(self.widget_7)
        self.lbSec.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbSec.setFont(font)
        self.lbSec.setStyleSheet("color:#ff0000")
        self.lbSec.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSec.setObjectName("lbSec")
        self.gridLayout_6.addWidget(self.lbSec, 2, 5, 1, 1)
        self.label_c = QtWidgets.QLabel(self.widget_7)
        self.label_c.setMinimumSize(QtCore.QSize(35, 15))
        self.label_c.setMaximumSize(QtCore.QSize(35, 15))
        self.label_c.setAlignment(QtCore.Qt.AlignCenter)
        self.label_c.setObjectName("label_c")
        self.gridLayout_6.addWidget(self.label_c, 1, 2, 1, 1)
        self.label_h = QtWidgets.QLabel(self.widget_7)
        self.label_h.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_h.setAlignment(QtCore.Qt.AlignCenter)
        self.label_h.setObjectName("label_h")
        self.gridLayout_6.addWidget(self.label_h, 1, 7, 1, 1)
        self.label_b = QtWidgets.QLabel(self.widget_7)
        self.label_b.setMinimumSize(QtCore.QSize(50, 0))
        self.label_b.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.label_b.setObjectName("label_b")
        self.gridLayout_6.addWidget(self.label_b, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.widget_7, 0, 0, 2, 3)
        self.mGroupBox_2 = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        self.mGroupBox_2.setObjectName("mGroupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.mGroupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.mGroupBox_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_4.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/remove_one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_10.addWidget(self.pushButton_4, 5, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.mGroupBox_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_3.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_10.addWidget(self.pushButton_3, 4, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 0, 0, 1, 1)
        self.cmbOrientacion = QtWidgets.QComboBox(self.mGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbOrientacion.setFont(font)
        self.cmbOrientacion.setObjectName("cmbOrientacion")
        self.gridLayout_10.addWidget(self.cmbOrientacion, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 0, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.mGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_10.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.mGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.mGroupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 0, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.mGroupBox_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_5.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/remove_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_10.addWidget(self.pushButton_5, 6, 4, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.mGroupBox_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.gridLayout_10.addWidget(self.tableWidget_2, 4, 0, 3, 4)
        self.gridLayout_8.addWidget(self.mGroupBox_2, 11, 0, 1, 4)
        self.mGroupBox = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        self.mGroupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.mGroupBox.setObjectName("mGroupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.mGroupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_14 = QtWidgets.QLabel(self.mGroupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.mGroupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidget, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.mGroupBox, 10, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 4, 2, 1, 1)
        self.leNumPredio = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leNumPredio.setFont(font)
        self.leNumPredio.setObjectName("leNumPredio")
        self.gridLayout_8.addWidget(self.leNumPredio, 5, 3, 1, 1)
        self.leNoExteAnt = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leNoExteAnt.setFont(font)
        self.leNoExteAnt.setObjectName("leNoExteAnt")
        self.gridLayout_8.addWidget(self.leNoExteAnt, 5, 2, 1, 1)
        self.leNoExteriorAlf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leNoExteriorAlf.setFont(font)
        self.leNoExteriorAlf.setObjectName("leNoExteriorAlf")
        self.gridLayout_8.addWidget(self.leNoExteriorAlf, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 2, 0, 1, 4)
        self.lbColonia = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbColonia.setFont(font)
        self.lbColonia.setObjectName("lbColonia")
        self.gridLayout_8.addWidget(self.lbColonia, 7, 2, 1, 1)
        self.lbCveCatAnt = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbCveCatAnt.setFont(font)
        self.lbCveCatAnt.setObjectName("lbCveCatAnt")
        self.gridLayout_8.addWidget(self.lbCveCatAnt, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 3, 1, 1)
        self.lbLocalidad = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbLocalidad.setFont(font)
        self.lbLocalidad.setObjectName("lbLocalidad")
        self.gridLayout_8.addWidget(self.lbLocalidad, 7, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 6, 3, 1, 1)
        self.lbNomMpio = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbNomMpio.setFont(font)
        self.lbNomMpio.setObjectName("lbNomMpio")
        self.gridLayout_8.addWidget(self.lbNomMpio, 9, 1, 1, 2)
        self.cmbTipoAsentH = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTipoAsentH.setFont(font)
        self.cmbTipoAsentH.setObjectName("cmbTipoAsentH")
        self.gridLayout_8.addWidget(self.cmbTipoAsentH, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 8, 0, 1, 1)
        self.lbCodigoPostal = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbCodigoPostal.setFont(font)
        self.lbCodigoPostal.setObjectName("lbCodigoPostal")
        self.gridLayout_8.addWidget(self.lbCodigoPostal, 7, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 4, 0, 1, 1)
        self.lbNoExt = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbNoExt.setFont(font)
        self.lbNoExt.setObjectName("lbNoExt")
        self.gridLayout_8.addWidget(self.lbNoExt, 5, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_8.addWidget(self.label_13, 8, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 6, 2, 1, 1)
        self.lbNomCalle = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lbNomCalle.setFont(font)
        self.lbNomCalle.setObjectName("lbNomCalle")
        self.gridLayout_8.addWidget(self.lbNomCalle, 3, 0, 1, 4)
        self.cmbTipoPredio = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cmbTipoPredio.setMinimumSize(QtCore.QSize(150, 30))
        self.cmbTipoPredio.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTipoPredio.setFont(font)
        self.cmbTipoPredio.setInputMethodHints(QtCore.Qt.ImhNone)
        self.cmbTipoPredio.setObjectName("cmbTipoPredio")
        self.gridLayout_8.addWidget(self.cmbTipoPredio, 1, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 8, 3, 1, 1)
        self.cmbRegimenProp = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbRegimenProp.setFont(font)
        self.cmbRegimenProp.setObjectName("cmbRegimenProp")
        self.gridLayout_8.addWidget(self.cmbRegimenProp, 9, 3, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.scrollArea_2, 1, 0, 2, 1)
        self.tabWidget.addTab(self.tUbicacion, "")
        self.tTerreno = QtWidgets.QWidget()
        self.tTerreno.setObjectName("tTerreno")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tTerreno)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_22 = QtWidgets.QLabel(self.tTerreno)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 12, 0, 1, 1)
        self.cmbFormaPredio = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbFormaPredio.setFont(font)
        self.cmbFormaPredio.setObjectName("cmbFormaPredio")
        self.gridLayout_11.addWidget(self.cmbFormaPredio, 11, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tTerreno)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tTerreno)
        self.label_28.setObjectName("label_28")
        self.gridLayout_11.addWidget(self.label_28, 10, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tTerreno)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 10, 1, 1, 1)
        self.leFrente = QtWidgets.QLineEdit(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leFrente.setFont(font)
        self.leFrente.setObjectName("leFrente")
        self.gridLayout_11.addWidget(self.leFrente, 9, 1, 1, 1)
        self.leFondo = QtWidgets.QLineEdit(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leFondo.setFont(font)
        self.leFondo.setObjectName("leFondo")
        self.gridLayout_11.addWidget(self.leFondo, 9, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tTerreno)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 8, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tTerreno)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 6, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tTerreno)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 2, 0, 1, 1)
        self.cmbTipoUsoSuelo = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTipoUsoSuelo.setFont(font)
        self.cmbTipoUsoSuelo.setObjectName("cmbTipoUsoSuelo")
        self.gridLayout_11.addWidget(self.cmbTipoUsoSuelo, 1, 0, 1, 1)
        self.cmbUsoPredio = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbUsoPredio.setFont(font)
        self.cmbUsoPredio.setObjectName("cmbUsoPredio")
        self.gridLayout_11.addWidget(self.cmbUsoPredio, 3, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tTerreno)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 0, 1, 1)
        self.leSupTerr = QtWidgets.QLineEdit(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.leSupTerr.setFont(font)
        self.leSupTerr.setObjectName("leSupTerr")
        self.gridLayout_11.addWidget(self.leSupTerr, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tTerreno)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 2, 1, 1, 1)
        self.cmbUsoSuelo = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbUsoSuelo.setFont(font)
        self.cmbUsoSuelo.setObjectName("cmbUsoSuelo")
        self.gridLayout_11.addWidget(self.cmbUsoSuelo, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tTerreno)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 8, 0, 1, 1)
        self.cmbTipoRelieve = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTipoRelieve.setFont(font)
        self.cmbTipoRelieve.setObjectName("cmbTipoRelieve")
        self.gridLayout_11.addWidget(self.cmbTipoRelieve, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tTerreno)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 0, 1, 1, 1)
        self.cmbOrientPredMza = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbOrientPredMza.setFont(font)
        self.cmbOrientPredMza.setObjectName("cmbOrientPredMza")
        self.gridLayout_11.addWidget(self.cmbOrientPredMza, 11, 1, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tTerreno)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_4, 13, 0, 1, 2)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tTerreno)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_3, 1, 2, 11, 1)
        self.label_27 = QtWidgets.QLabel(self.tTerreno)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 4, 0, 1, 1)
        self.cmbFacilComun = QtWidgets.QComboBox(self.tTerreno)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cmbFacilComun.setFont(font)
        self.cmbFacilComun.setObjectName("cmbFacilComun")
        self.gridLayout_11.addWidget(self.cmbFacilComun, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tTerreno, "")
        self.tConstrPred = QtWidgets.QWidget()
        self.tConstrPred.setObjectName("tConstrPred")
        self.tabWidget.addTab(self.tConstrPred, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_5)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 363, 889))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(345, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_7.addWidget(self.lineEdit_4, 0, 0, 1, 1)
        self.dial_5 = QtWidgets.QDial(self.scrollAreaWidgetContents)
        self.dial_5.setMinimumSize(QtCore.QSize(345, 50))
        self.dial_5.setObjectName("dial_5")
        self.gridLayout_7.addWidget(self.dial_5, 5, 0, 1, 1)
        self.dial_4 = QtWidgets.QDial(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_4.sizePolicy().hasHeightForWidth())
        self.dial_4.setSizePolicy(sizePolicy)
        self.dial_4.setMinimumSize(QtCore.QSize(345, 50))
        self.dial_4.setObjectName("dial_4")
        self.gridLayout_7.addWidget(self.dial_4, 4, 0, 1, 1)
        self.dial_6 = QtWidgets.QDial(self.scrollAreaWidgetContents)
        self.dial_6.setMinimumSize(QtCore.QSize(345, 50))
        self.dial_6.setObjectName("dial_6")
        self.gridLayout_7.addWidget(self.dial_6, 2, 0, 1, 1)
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_4.setMinimumSize(QtCore.QSize(345, 300))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.gridLayout_7.addWidget(self.textBrowser_4, 8, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setMinimumSize(QtCore.QSize(345, 10))
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 7, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.textBrowser_3.setMinimumSize(QtCore.QSize(345, 300))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout_7.addWidget(self.textBrowser_3, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(345, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_7.addWidget(self.lineEdit_5, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget_5)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 80))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.widget_3)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_2.addWidget(self.listWidget, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1030, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionuno_2 = QtWidgets.QAction(MainWindow)
        self.actionuno_2.setObjectName("actionuno_2")
        self.actiondos_2 = QtWidgets.QAction(MainWindow)
        self.actiondos_2.setObjectName("actiondos_2")
        self.menu.addAction(self.actionGuardar)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSalir)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cedula"))
        self.lbCveCata.setText(_translate("MainWindow", "00-000-000-00-0000-000-000-00000"))
        self.pushButton_2.setText(_translate("MainWindow", "Guardar"))
        self.lbPredio.setText(_translate("MainWindow", "00000"))
        self.label_0.setText(_translate("MainWindow", "Clave Catastral Cartografica"))
        self.lbEdo.setText(_translate("MainWindow", "00"))
        self.lbLoc.setText(_translate("MainWindow", "0000"))
        self.label_d.setText(_translate("MainWindow", "Secc."))
        self.label_g.setText(_translate("MainWindow", "Mza."))
        self.label_e.setText(_translate("MainWindow", "Loc."))
        self.lbRegCat.setText(_translate("MainWindow", "000"))
        self.label_f.setText(_translate("MainWindow", "Sector"))
        self.label_a.setText(_translate("MainWindow", "Edo."))
        self.lbSecc.setText(_translate("MainWindow", "00"))
        self.lbMpio.setText(_translate("MainWindow", "000"))
        self.lbMza.setText(_translate("MainWindow", "000"))
        self.lbSec.setText(_translate("MainWindow", "000"))
        self.label_c.setText(_translate("MainWindow", "Mpio."))
        self.label_h.setText(_translate("MainWindow", "Predio"))
        self.label_b.setText(_translate("MainWindow", "Reg. Cat."))
        self.mGroupBox_2.setTitle(_translate("MainWindow", "Colindancias"))
        self.label_15.setText(_translate("MainWindow", "Orientacion"))
        self.label_17.setText(_translate("MainWindow", "Descripcion"))
        self.label_16.setText(_translate("MainWindow", "Dist. Perimetral"))
        self.mGroupBox.setTitle(_translate("MainWindow", "Vialidades"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "No. Exterior Alf"))
        self.label_6.setText(_translate("MainWindow", "Num. Predio"))
        self.label_5.setText(_translate("MainWindow", "No. Exterior Ant"))
        self.label_2.setText(_translate("MainWindow", "Nombre de Vialidad/Calle"))
        self.lbColonia.setText(_translate("MainWindow", "lbColonia"))
        self.lbCveCatAnt.setText(_translate("MainWindow", "lbCveCatAnt"))
        self.label.setText(_translate("MainWindow", "Tipo de Predio"))
        self.lbLocalidad.setText(_translate("MainWindow", "lbLocalidad"))
        self.label_11.setText(_translate("MainWindow", "Localidad"))
        self.lbNomMpio.setText(_translate("MainWindow", "lbNomMpio"))
        self.label_12.setText(_translate("MainWindow", "Clave Catastral Anterior"))
        self.lbCodigoPostal.setText(_translate("MainWindow", "lbCodigoPostal"))
        self.label_7.setText(_translate("MainWindow", "Codigo Postal"))
        self.label_3.setText(_translate("MainWindow", "No. Exterior"))
        self.lbNoExt.setText(_translate("MainWindow", "lbNoExt"))
        self.label_13.setText(_translate("MainWindow", "Nombre del Municipio"))
        self.label_8.setText(_translate("MainWindow", "Tipo Asentamiento Humano"))
        self.label_10.setText(_translate("MainWindow", "Colonia"))
        self.lbNomCalle.setText(_translate("MainWindow", "lbNomCalle"))
        self.label_30.setText(_translate("MainWindow", "Regimen de Propiedad"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tUbicacion), _translate("MainWindow", "Ubicacion"))
        self.label_22.setText(_translate("MainWindow", "Servicios de Predio"))
        self.label_21.setText(_translate("MainWindow", "Servicios de Calle"))
        self.label_28.setText(_translate("MainWindow", "Forma de Predio"))
        self.label_29.setText(_translate("MainWindow", "Orientacion del Predio dentro de la Manzana"))
        self.label_25.setText(_translate("MainWindow", "Frente"))
        self.label_26.setText(_translate("MainWindow", "Superficie de Terreno"))
        self.label_20.setText(_translate("MainWindow", "Uso de Predio"))
        self.label_19.setText(_translate("MainWindow", "Tipo Uso de Suelo"))
        self.label_23.setText(_translate("MainWindow", "Tipo de Relieve"))
        self.label_24.setText(_translate("MainWindow", "Fondo"))
        self.label_18.setText(_translate("MainWindow", "Uso de Suelo"))
        self.label_27.setText(_translate("MainWindow", "Facilidad de Comunicacion"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tTerreno), _translate("MainWindow", "Terreno"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tConstrPred), _translate("MainWindow", "Construcciones"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menu.setTitle(_translate("MainWindow", "Archivo"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionuno_2.setText(_translate("MainWindow", "uno"))
        self.actiondos_2.setText(_translate("MainWindow", "dos"))

from qgis.gui import QgsCollapsibleGroupBox
